### ISSUE TITLE
[training] Complete TODOMVC of vuejs

### ISSUE THREAD

**Issue by lanshunfang** [williamlifaith/4-quadrants#4]
https://vuejs.org/v2/examples/todomvc.html

**Comment by sirkay777** [comment]
https://jsfiddle.net/sirkay777/woynLoqb/26/ 
Almost finished.
I skimmed through the Vue documentations, especially the  part about components, looking for similar concepts in React. I think I finished the Todo app in a React way.
I have a few questions about where to store state and how children component change the state by firing event. I will ask them in Monday meeting.

**Comment by lanshunfang** [comment]
BTW, please add comment in English.

**Comment by sirkay777** [comment]
@lanshunfang Updated my prvious comment in English.

**Comment by sirkay777** [comment]
https://jsfiddle.net/sirkay777/woynLoqb/32
Updated!
